//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Acme.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Campoes
    {
        public int Id { get; set; }
        public string Nombre { get; set; }
        public string Titulo { get; set; }
        public bool EsRequerido { get; set; }
        public int TipoCampo { get; set; }
        public int EncuestaId { get; set; }
    
        public virtual Encuestas Encuestas { get; set; }
    }
}
